version: 2
jobs:
  build-test:
    working_directory: ~/RioDoCampoLimpo
    docker:
      - image: node:8-alpine
      - image: circleci/postgres:12-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: riodocampo_testing
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-2-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Instalando pacotes
          command: npm i
      - save_cache:
          key: dependency-cache-2-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Copiando .env
          command: cp .env.example .env
      - run:
          name: Executando testes
          command: npm test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/RioDoCampoLimpo
    steps:
      - checkout
      - run:
          name: "Fazendo deploy"
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/riodocampolimpo.git master

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master
