version: 2
jobs:
  build-test:
    working_directory: ~/RioDoCampoLimpo
    docker:
      - image: node:10
      - image: mongo:4
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: 
          name: Instalando pacotes
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Executando testes 
          command: npm test

  deploy:
    docker:
      - image: buildpack-deps:trusty
    working_directory: ~/RioDoCampoLimpo
    steps:
      - checkout
      - run:
          name: "Fazendo deploy para Heroku"
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/riodocampolimpo.git master
  
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-test:
          filters:
            branches:
              ignore: master
      - deploy:
          filters:
            branches:
              only: master